### Variables
@baseUrl = http://localhost:3000
@authToken = 
@productId = aff2c450-a00d-41ae-ad7c-6cc7f7abadfe

## Get all products
GET {{baseUrl}}/products

### Add item to cart
POST {{baseUrl}}/cart/add
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "productId": "{{productId}}",
  "quantity": 10
}

### Get user cart
GET {{baseUrl}}/cart
Authorization: Bearer {{authToken}}

### Get cart total
GET {{baseUrl}}/cart/total
Authorization: Bearer {{authToken}}

### Increase quantity of cart item
POST {{baseUrl}}/cart/your-cart-item-id/increase
Authorization: Bearer {{authToken}}

### Decrease quantity of cart item
POST {{baseUrl}}/cart/your-cart-item-id/decrease
Authorization: Bearer {{authToken}}

### Remove item from cart
DELETE {{baseUrl}}/cart/your-cart-item-id
Authorization: Bearer {{authToken}}

### Clear all items from cart
DELETE {{baseUrl}}/cart
Authorization: Bearer {{authToken}}

### Checkout and send order confirmation email
POST {{baseUrl}}/cart/checkout
Authorization: Bearer {{authToken}}

### Get purchase history
GET {{baseUrl}}/cart/purchase-history
Authorization: Bearer {{authToken}} 