### Variables
@baseUrl = http://localhost:3000
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNjY5YTEyYi0yZTA4LTRjOWQtODljZi0wNTc5YzMwOTU2MTAiLCJlbWFpbCI6ImRlZUBleGFtcGxlLmNvbSIsInJvbGUiOiJDVVNUT01FUiIsImlhdCI6MTc1MDM1NTI2NiwiZXhwIjoxNzUwNDQxNjY2fQ.wyIBLssQra7pYv-wziDEZRSZnI8iYqEwTLw6VNcIGvU
@productId = aff2c450-a00d-41ae-ad7c-6cc7f7abadfe

## Get all products
GET {{baseUrl}}/products

### Add item to cart
POST {{baseUrl}}/cart/add
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "productId": "{{productId}}",
  "quantity": 10
}

### Get user cart
GET {{baseUrl}}/cart
Authorization: Bearer {{authToken}}

### Remove item from cart
DELETE {{baseUrl}}/cart/cart_item_id
Authorization: Bearer {{authToken}} 