@baseUrl = http://localhost:3000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ZjZlZDEwOS1jZmFlLTQwNDEtYWEyMi1lMWZmNTU2YjUzMTEiLCJlbWFpbCI6ImNlZUBleGFtcGxlLmNvbSIsInJvbGUiOiJDVVNUT01FUiIsImlhdCI6MTc1MDMzMjc3OCwiZXhwIjoxNzUwNDE5MTc4fQ.df-MGzZwUMXecl3znLUQUHequ0mZLzpXeoSQ_fxtDHU

### Create a new product (Admin only)
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "name": "iPhone 15 Pro",
  "description": "Latest Apple iPhone with advanced camera system",
  "price": 999.99,
  "quantity": 50,
  "imageUrl": "https://example.com/iphone15.jpg",
  "stockQuantity": 50
}

### Get all products (public)
GET {{baseUrl}}/products

### Get product by name (public)
GET {{baseUrl}}/products?name=I

### Get a specific product (public)
GET {{baseUrl}}/products/32099f3a-be36-49af-9415-b88e2133f034

### Update a product (Admin only)
PUT {{baseUrl}}/products/32099f3a-be36-49af-9415-b88e2133f034
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "iPhone 15 Pro Max",
  "description": "Latest Apple iPhone with advanced camera system and larger display",
  "price": 1099.99,
  "imageUrl": "https://example.com/iphone15promax.jpg",
  "stockQuantity": 30
}

### Delete a product (Admin only)
DELETE {{baseUrl}}/products/32099f3a-be36-49af-9415-b88e2133f034
Authorization: Bearer {{token}}