@baseUrl = http://localhost:3000


### Login as Admin 
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin123"
}

###  JWT Token 
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNjY5YTEyYi0yZTA4LTRjOWQtODljZi0wNTc5YzMwOTU2MTAiLCJlbWFpbCI6ImRlZUBleGFtcGxlLmNvbSIsInJvbGUiOiJDVVNUT01FUiIsImlhdCI6MTc1MDM1NTI2NiwiZXhwIjoxNzUwNDQxNjY2fQ.wyIBLssQra7pYv-wziDEZRSZnI8iYqEwTLw6VNcIGvU


### Upload  Product Image 
POST {{baseUrl}}/products/upload-image
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="product-image.jpg"
Content-Type: image/jpg

< ./product-image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###  Image URL 
@imageUrl = https://res.cloudinary.com/duymwzfhj/image/upload/v1750354853/shopie/products/images/file_bfkc01.jpg
@productId = ee99b449-db97-4bce-877c-267b0ce8203a



### Creating Product with Uploaded Image
POST {{baseUrl}}/products
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "IPhone 13 Pro ",
  "description": "A test product with uploaded image",
  "price": 1900.99,
  "imageUrl": "{{imageUrl}}",
  "stockQuantity": 100
}

### Get All Products
GET {{baseUrl}}/products

### Get  Product by ID
GET {{baseUrl}}/products/{{productId}}


### Delete Product
DELETE {{baseUrl}}/products/{{productId}}
Authorization: Bearer {{authToken}}

### Delete Image from Cloudinary
DELETE {{baseUrl}}/products/image/{{productId}}
Authorization: Bearer {{authToken}}
