@baseUrl = http://localhost:3000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNjY5YTEyYi0yZTA4LTRjOWQtODljZi0wNTc5YzMwOTU2MTAiLCJlbWFpbCI6ImRlZUBleGFtcGxlLmNvbSIsInJvbGUiOiJDVVNUT01FUiIsImlhdCI6MTc1MDM1NTI0NiwiZXhwIjoxNzUwNDQxNjQ2fQ.EChc5JH5PB6YDfjKspbvmYBFVwOx9cJeZB1ks33tJMY

@id = 0669a12b-2e08-4c9d-89cf-0579c3095610

### Register a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "dee ",
  "email": "dee@example.com",
  "password": "dee@example.com"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "dee@example.com",
  "password": "dee@example.com"
}

### Create a new user(ADMIN)
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Admin User",
  "email": "admin@example.com",
  "password": "admin123",
  "role": "ADMIN"
}

### Login as Admin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "eddy.new@example.com",
  "password": "12345678"
}

### Get all users (Admin only)
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

### Get user profile (own profile only)
GET {{baseUrl}}/users/profile
Authorization: Bearer {{token}}

### Get user by id (Admin only)
GET {{baseUrl}}/users/{{id}}
Authorization: Bearer {{token}}

### Update own profile (only name and email)
PUT {{baseUrl}}/users/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Eddy Max Kilonzo",
  "email": "eddy.new@example.com"
}

### Reset password (secure - only own password)
POST {{baseUrl}}/auth/reset-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "currentPassword": "eddy@example.com",
  "newPassword": "12345678"
}

### Delete own profile
DELETE {{baseUrl}}/users/profile
Authorization: Bearer {{token}}

### Delete user (Admin only)
DELETE {{baseUrl}}/users/{{id}}
Authorization: Bearer {{token}}
