@baseUrl = http://localhost:3000

@token =

### Register a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Test User",
  "email": "user@example.com",
  "password": "password123"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}

### Create a new user(ADMIN)
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Admin User",
  "email": "admin@example.com",
  "password": "admin123",
  "role": "ADMIN"
}
### Login as Admin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin123"
}

### Get all users
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

### Get user profile
GET {{baseUrl}}/users/profile
Authorization: Bearer {{token}}

### Get user by id
GET {{baseUrl}}/users/<id>
Authorization: Bearer {{token}}

### Update user
PUT {{baseUrl}}/users/<id>
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Updated Name"
}
### Update user password
PUT {{baseUrl}}/users/<id>/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "password": "12345678"
}

### Delete user
DELETE {{baseUrl}}/users/<id>
Authorization: Bearer {{token}}
